{{- if .Values.ingress.enabled -}}
{{- $fullName := include "kibana.fullname" . -}}
{{- $httpPort := .Values.httpPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "kibana.fullname" . }}
  labels: {{ include "kibana.labels" . | nindent 4 }}
  annotations:
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: "/"
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    traefik.ingress.kubernetes.io/app-root: "/app/"
    traefik.ingress.kubernetes.io/preserve-host: "true"
  labels:
    app.kubernetes.io/name: {{ template "kibana.fullname" . }}
spec:
  rules:
  - http:
      paths:
      - path: /kibana
        pathType: Prefix
        backend:        
          service: 
            name: "kibana"
            port: 
              number: 5601
{{- end }}